version: "3.8"
services:
  front:
    build: ./ #DockerFile のあるディレクトリのパスを指定（左記はカレントディレクトリを指定）
    container_name: stock-front2
    volumes:
      - ./:/usr/app/stock-front2 #ホストからバインドマウント
      - stock_front2_node_modules_volumes:/usr/app/stock-front2/node_modules # node_modulesはホストと共有しないでnamed volumeマウント
    working_dir: /usr/app/stock-front2
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes: 
  stock_front2_node_modules_volumes: 
